### ISSUE TITLE
server.stop seems to leave command line prompt hanging

### ISSUE THREAD

**Issue by jdann** [gimm/gulp-express#24]
I have a set of 3 gulp tasks that starts the server, runs some automated tests and then closes the server. However, when I run them the command prompt hangs after the server has been stopped.

Not sure if I have configured something wrong in gulp or if this is an issue with server,stop

GULP TASKS
gulp.task('integration-express', function () {
  // Start the server at the beginning of the task
  return server.run({
    file: paths.config + 'server.js'
  });
});

gulp.task('integration-run', ['integration-express'],  function(){
  var protractor = 'protractor ./config/protractor.conf.js';
  return gulp.src('')
      .pipe(plumber())
      .pipe(plugins.shell([protractor]))
	  .pipe(gulp.dest('./dist'));
});

gulp.task('integration', ['integration-run'],  function(){
	server.stop();
});

COMMAND LINE
[14:13:16] Finished 'integration-run' after 22 s
[14:13:16] Starting 'integration'...
[14:13:16] Finished 'integration' after 523 µs
Service process exited with code null SIGKILL
^CTerminate batch job (Y/N)?

**Comment by gimm** [comment]
I've added:
```
process.on('SIGINT', function(){
  process.exit();
});
```
please let me know this works for you

**Comment by jdann** [comment]
It's still hanging. I am getting the following now:

[08:40:46] Finished 'integration-run' after 1.45 min
[08:40:46] Starting 'integration'...
[08:40:46] Finished 'integration' after 409 µs
Service process exited with [code => null | sig => SIGKILL]
Service process exited with [code => undefined | sig => undefined]
Service process exited with [code => 0 | sig => undefined]

**Comment by gimm** [comment]
Thanks for your feedback, I will look into this later. The Chinese New Year is coming, so please be patient😉

**Comment by jdann** [comment]
That's fine. Just to confirm the commands are being run from a Windows 7 PC

**Comment by DanPantry** [comment]
This appears to be something to do with `tiny-lr`. Removing the livereload functionality causes the task to end as expected. Been having this problem for the longest time myself. I'm going to look into it and see if I can dig something up while @gimm is celebrating new year

**Comment by DanPantry** [comment]
After poking around `tiny-lr`, I found it was starting a `listen` on a node http server, but `gulp-express` was not capturing the server, so when the child process of express ended, livereload was not having it's http server closed, and so the livereload server was keeping the task alive.

I fixed this by causing `Server.prototype.listen` in `tiny-lr/server.js` to return `this.server` and then adding the following code to `gulp-express`:

````
            var livereloadServer;

            if (node) { // Stop
                node.kill('SIGKILL');
                node = undefined;
                process.removeListener('exit', processExitListener);
            } else {
                livereloadServer = livereload.start(options.port);
            }
````

````            
node.on('exit', function() {
  livereloadServer.close();
});
````

Now you can return the result of `gulp-express`'s `run` method and gulp will terminate the task correctly. Not pretty but it works. This should do while we wait for @gimm  to come up with a more permanent fix as I feel this is quite a hacky fix and wouldn't be comfortable putting it as a pull request.

**Comment by gimm** [comment]
@DanPantry thanks man, I have update the plugin:
```js
nodeExit: function (code, sig) {
            console.log('Node process exited with [code => %s | sig => %s]', code, sig);
            lr.close();//this will close tiny-lr server when node process exit
        }
```
this should stop the hanging.

**Comment by DanPantry** [comment]
Glad to be of service.

--- Original Message ---

**Comment by jdann** [comment]
Thank you both - that's fixed the problem for me
