### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by matpimenta** [gimm/gulp-express#29]
Currently, there's no way to start tiny-lr in HTTPS. When I run express in HTTPS, livereload doesn't work as browsers block requests to protocols different from HTTPS.

**Comment by gimm** [comment]
new version is out there, thanks.

**Comment by matpimenta** [comment]
I think my pull request introduced a bug. The 'fileName' is now in the wrong case.

        reload: function (fileName) {
            if (lr != undefined) {
                lr.changed({
                    body: {
                        files: [filename]
                    }
                });
            } else {
                console.log('tinylr not started');
                node && node.kill();
            }
        }
