### ISSUE TITLE
Debug module not logging data

### ISSUE THREAD

**Issue by nathanbuchar** [gimm/gulp-express#31]
Since the switch to using Debug ([c6ef9d2](https://github.com/gimm/gulp-express/commit/c6ef9d25a1d42169b34520f821e39cac6c42aa8c)), the node process is no longer logging data into Terminal.

Data is passed correctly into the local `logData` method—`console.log(data.trim())` confirms this—however somewhere along the lines, the Debug module is not outputting the data.

**Comment by gimm** [comment]
You need to set `DEBUG` environment variable in order to get it work, that's how `DEBUG` works.

**Comment by nathanbuchar** [comment]
I do in fact already have `DEBUG` set to `true`.

```bash
echo $DEBUG
--> true
```

I have also hard-coded the environment variable into the top of `gulpfile.js` to be absolutely certain that the environment variable is getting through.
```javascript
process.env.DEBUG = true;
process.env.debug = true;
```

Still no dice

**Comment by nathanbuchar** [comment]
Oh, I see how Debug works now. It needs the process namespace(s), not a boolean.

```bash
export DEBUG=gulp:express
```
