### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by Microx** [gimm/gulp-express#32]
Why do you erase support for console.log from gulp.express?

Now I have to add listener on stdout and stderr.

**Comment by randy-sesser-locm** [comment]
@Microx I figured out that if you pass `options.stdio = 'inherit'` you get your logging back. Problem now is there's an null reference error on [line 81](https://github.com/gimm/gulp-express/blob/master/index.js#L81).

**Comment by thesciz** [comment]
I'd love a solution to this as well! Particularly the null reference error.

**Comment by thesciz** [comment]
I've found a quick workaround. Instead of setting options.stdio, don't pass any options and just change line 63 in node_modules/gulp_express/index.js: from `debug(data.trim());` to `console.log(data.trim());`

**Comment by Microx** [comment]
Yes, it's possible.

I have to add listener for gulp task.

```javascript
        node.stdout.on('data', function(data) {
		console.log(data.trim());
	});

	node.stderr.on('data', function(data) {
		console.error(data.trim());
	});
```

**Comment by gimm** [comment]
please update to version 0.2.0 manually
