### ISSUE TITLE
LiveReload breaks on server restart

### ISSUE THREAD

**Issue by thesciz** [gimm/gulp-express#35]
Whenever any code changes are noticed in the following files:

`gulp.watch(['app.js', 'routes/**/*.js', 'app/**/*.js'], [server.run]);`

Livereload stops working in the browser:

`WebSocket connection to 'ws://192.168.1.60:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Is there a way to simply restart the gulp process or to circumvent this error?

**Comment by gimm** [comment]
I've verified this problem, my suggestion is:
```js
server.run();
gulp.watch(['app.js', 'routes/**/*.js', 'app/**/*.js'], server.notify);
```
this works for me.

**Comment by Microx** [comment]
I have same problem..

It doesn't solve my problem, where I have isomorphic application and I need to restart server and notify about changes for reload.

**Comment by thesciz** [comment]
Hey gimm,

Still no dice. Notify seems to just trigger the livereload of static assets, but won't restart the Node server itself. `server.run` accomplishes this, but livereload is broken until I quit and restart the gulp process.

**Comment by gimm** [comment]
@thesciz @Microx the new release v0.3.0 should solve this problem.
please let me know if it doesn't.

**Comment by Microx** [comment]
Hi gimm,

v0.3.0 resolve my problem. Now everything working right.

Thanks

**Comment by gimm** [comment]
@Microx np, thanks for feedback!
