### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Microx** [gimm/gulp-express#37]
Hi,

I have verison 0.3.0 and I got more times this error. Maybe it could be something with livereload and for me livereload is again destroyed.

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at process.addListener (events.js:160:15)
  at process.on.process.addListener (node.js:773:26)
  at Object.module.exports.run node_modules/gulp-express/index.js:104:21)

**Comment by gimm** [comment]
@Microx v0.3.2 should fix this multi listeners issue.

**Comment by Microx** [comment]
I quick tried it and it looks that is fixed now.

Thanks..
