### ISSUE TITLE
file options revert to default (app.js) on gulp.watch initiated server restart (server.run)

### ISSUE THREAD

**Issue by diffalot** [gimm/gulp-express#5]
this issue has been fixed on the master branch but has not made it to the npm package; leaving this note here for anyone having trouble after `npm install gulp-express`

``` javascript
  server.run({
    file: './server'
  });
  gulp.watch('./server/**/*', server.run);
```

when a file in `./server/` is changed, gulp watch sends the path of the changed file to `server.run` in place of the previously set `file` option, so the server tries to run `app.js`, the default `file` option, resulting in the error:

```
Error: Cannot find module '/home/user/code/project/app.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

as i've said, this is fixed in master, so just download index.js from this repo and use it to replace the index.js that was installed in node_modules.

:heart: this project, it's wonderful :+1:

**Comment by nicgirault** [comment]
@xiwcx, @gimm, I've run into the same problem

**Comment by xiwcx** [comment]
@nicgirault can you share the relevant part of your gulpfile as well as your os, node, and gulp-express versions so we can try to figure out who is still effected by the bug? thanks.
